<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Trend-Corner Technical Test - Samved Mohan Vajpeyi</title>

  <!-- Loading Bootstrap CSS and JS libraries from CDN -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

</head>

<body>
  <!-- Navigation -->
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="index.php">Trend-Corner Test</a>
      </div>
      <ul class="nav navbar-nav">
        <li class="active"><a href="index.php">Home</a></li>
      </ul>
    </div>
  </nav>
  <!-- Page Content -->

  <div class="container">
    <div class="col-lg-3"></div>
    <div class="col-lg-6">
      <div class="jumbotron">

        <!-- Display error/success message -->
        <?=(isset($msg)) ? $msg : ""?>

          <h2>Upload CSV to database!</h2>

          <form action="<?= $router->pathFor('upload') ?>" method="post" enctype="multipart/form-data">
            <div class="form-group">
              <label for="csv">Select CSV file to upload:</label>
              <input type="file" name="csv" id="csv" class="form-control">
            </div>
            <button type="submit" name="submit" class="btn btn-default">Upload CSV</button>
          </form>

      </div>

      <table class="table">
        <thead>
          <tr>
            <th>Id</th>
            <th>File Name</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
        <?php foreach($files as $file) : ?>
          <tr>
            <td><?=  $file["id"] ?></td>
            <td><?=  $file["name"] ?></td>
            <td></td>
          </tr>
        <?php endforeach; ?>
        </tbody>
      </table>
    </div>
    <div class="col-lg-3"></div>
    <!-- Footer -->
    <footer>
      <div class="navbar-fixed-bottom">
        <div class="col-lg-12">
        </div>
      </div>
    </footer>
  </div>
  <!-- /.container -->

</body>

</html>
